# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(480, 594)
        MainWindow.setMinimumSize(QtCore.QSize(472, 594))
        MainWindow.setMaximumSize(QtCore.QSize(480, 594))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_cpu = QtWidgets.QLabel(self.centralwidget)
        self.label_cpu.setGeometry(QtCore.QRect(20, 120, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_cpu.setFont(font)
        self.label_cpu.setObjectName("label_cpu")
        self.label_memory = QtWidgets.QLabel(self.centralwidget)
        self.label_memory.setGeometry(QtCore.QRect(230, 120, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_memory.setFont(font)
        self.label_memory.setObjectName("label_memory")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 30, 361, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 150, 156, 15))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_cpu_count = QtWidgets.QLabel(self.layoutWidget1)
        self.label_cpu_count.setText("")
        self.label_cpu_count.setObjectName("label_cpu_count")
        self.horizontalLayout_2.addWidget(self.label_cpu_count)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 170, 101, 15))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_cpu_freq = QtWidgets.QLabel(self.layoutWidget2)
        self.label_cpu_freq.setText("")
        self.label_cpu_freq.setObjectName("label_cpu_freq")
        self.horizontalLayout_3.addWidget(self.label_cpu_freq)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(230, 170, 107, 15))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_memory_free = QtWidgets.QLabel(self.layoutWidget3)
        self.label_memory_free.setText("")
        self.label_memory_free.setObjectName("label_memory_free")
        self.horizontalLayout_4.addWidget(self.label_memory_free)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(230, 150, 111, 16))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_memory_total = QtWidgets.QLabel(self.layoutWidget4)
        self.label_memory_total.setText("")
        self.label_memory_total.setObjectName("label_memory_total")
        self.horizontalLayout_5.addWidget(self.label_memory_total)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(350, 170, 102, 15))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.label_memory_used = QtWidgets.QLabel(self.layoutWidget5)
        self.label_memory_used.setText("")
        self.label_memory_used.setObjectName("label_memory_used")
        self.horizontalLayout_6.addWidget(self.label_memory_used)
        self.label_cpu_percent = QtWidgets.QLabel(self.centralwidget)
        self.label_cpu_percent.setGeometry(QtCore.QRect(70, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cpu_percent.setFont(font)
        self.label_cpu_percent.setText("")
        self.label_cpu_percent.setObjectName("label_cpu_percent")
        self.label_memory_percent = QtWidgets.QLabel(self.centralwidget)
        self.label_memory_percent.setGeometry(QtCore.QRect(290, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_memory_percent.setFont(font)
        self.label_memory_percent.setText("")
        self.label_memory_percent.setObjectName("label_memory_percent")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 80, 481, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 350, 481, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_cpu_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_cpu_2.setGeometry(QtCore.QRect(20, 390, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_cpu_2.setFont(font)
        self.label_cpu_2.setObjectName("label_cpu_2")
        self.label_cpu_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_cpu_3.setGeometry(QtCore.QRect(20, 470, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_cpu_3.setFont(font)
        self.label_cpu_3.setObjectName("label_cpu_3")
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 430, 230, 15))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.label_disk_usage = QtWidgets.QLabel(self.layoutWidget6)
        self.label_disk_usage.setText("")
        self.label_disk_usage.setObjectName("label_disk_usage")
        self.horizontalLayout_7.addWidget(self.label_disk_usage)
        self.layoutWidget7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 510, 109, 15))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.label_net_sent = QtWidgets.QLabel(self.layoutWidget7)
        self.label_net_sent.setText("")
        self.label_net_sent.setObjectName("label_net_sent")
        self.horizontalLayout_8.addWidget(self.label_net_sent)
        self.layoutWidget8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget8.setGeometry(QtCore.QRect(151, 510, 121, 16))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.label_net_recv = QtWidgets.QLabel(self.layoutWidget8)
        self.label_net_recv.setText("")
        self.label_net_recv.setObjectName("label_net_recv")
        self.horizontalLayout_9.addWidget(self.label_net_recv)
        self.widget_cpu = PlotWidget(self.centralwidget)
        self.widget_cpu.setGeometry(QtCore.QRect(20, 210, 211, 131))
        self.widget_cpu.setObjectName("widget_cpu")
        self.widget_ram = PlotWidget(self.centralwidget)
        self.widget_ram.setGeometry(QtCore.QRect(240, 210, 211, 131))
        self.widget_ram.setObjectName("widget_ram")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.label.show) # type: ignore
        self.pushButton.clicked.connect(self.label_cpu_count.show) # type: ignore
        self.pushButton.clicked.connect(self.label_cpu_freq.show) # type: ignore
        self.pushButton.clicked.connect(self.label_3.show) # type: ignore
        self.pushButton_2.clicked.connect(self.label_cpu_count.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_cpu_freq.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_3.hide) # type: ignore
        self.pushButton.clicked.connect(self.label_cpu.show) # type: ignore
        self.pushButton.clicked.connect(self.label_memory.show) # type: ignore
        self.pushButton_2.clicked.connect(self.label_cpu.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_memory.hide) # type: ignore
        self.pushButton.clicked.connect(self.label_7.show) # type: ignore
        self.pushButton.clicked.connect(self.label_memory_free.show) # type: ignore
        self.pushButton.clicked.connect(self.label_memory_total.show) # type: ignore
        self.pushButton.clicked.connect(self.label_9.show) # type: ignore
        self.pushButton_2.clicked.connect(self.label_7.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_memory_free.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_9.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_memory_total.hide) # type: ignore
        self.pushButton.clicked.connect(self.label_11.show) # type: ignore
        self.pushButton.clicked.connect(self.label_memory_used.show) # type: ignore
        self.pushButton_2.clicked.connect(self.label_11.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_memory_used.hide) # type: ignore
        self.pushButton.clicked.connect(self.label_cpu_2.show) # type: ignore
        self.pushButton.clicked.connect(self.label_2.show) # type: ignore
        self.pushButton.clicked.connect(self.label_disk_usage.show) # type: ignore
        self.pushButton.clicked.connect(self.label_cpu_3.show) # type: ignore
        self.pushButton.clicked.connect(self.label_5.show) # type: ignore
        self.pushButton.clicked.connect(self.label_net_sent.show) # type: ignore
        self.pushButton.clicked.connect(self.label_6.show) # type: ignore
        self.pushButton.clicked.connect(self.label_net_recv.show) # type: ignore
        self.pushButton.clicked.connect(self.line.show) # type: ignore
        self.pushButton.clicked.connect(self.line_2.show) # type: ignore
        self.pushButton_2.clicked.connect(self.line.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.line_2.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_cpu_2.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_2.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_disk_usage.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_cpu_3.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_5.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_net_sent.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_6.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_net_recv.hide) # type: ignore
        self.pushButton.clicked.connect(self.label_cpu_percent.show) # type: ignore
        self.pushButton.clicked.connect(self.label_memory_percent.show) # type: ignore
        self.pushButton_2.clicked.connect(self.label_cpu_percent.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.label_memory_percent.hide) # type: ignore
        self.pushButton.clicked.connect(self.widget_cpu.show) # type: ignore
        self.pushButton.clicked.connect(self.widget_ram.show) # type: ignore
        self.pushButton_2.clicked.connect(self.widget_cpu.hide) # type: ignore
        self.pushButton_2.clicked.connect(self.widget_ram.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_cpu.setText(_translate("MainWindow", "CPU"))
        self.label_memory.setText(_translate("MainWindow", "RAM"))
        self.pushButton.setText(_translate("MainWindow", "Монитор ресурсов"))
        self.pushButton_2.setText(_translate("MainWindow", "Монитор процессов"))
        self.label.setText(_translate("MainWindow", "Число процессоров:"))
        self.label_3.setText(_translate("MainWindow", "Частота:"))
        self.label_7.setText(_translate("MainWindow", "Свободно:"))
        self.label_9.setText(_translate("MainWindow", "Всего памяти:"))
        self.label_11.setText(_translate("MainWindow", "Занято:"))
        self.label_cpu_2.setText(_translate("MainWindow", "DISK"))
        self.label_cpu_3.setText(_translate("MainWindow", "NET"))
        self.label_2.setText(_translate("MainWindow", "Занято места на системном диске:"))
        self.label_5.setText(_translate("MainWindow", "Отправка:"))
        self.label_6.setText(_translate("MainWindow", "Получение:"))
from pyqtgraph import PlotWidget
